name: versioning
inputs:
  target_branch:
    required: false
runs:
  using: composite
  steps:
  - name: Tag build
    env:
      TARGET_BRANCH: ${{ inputs.target_branch }}
    run: echo "${TARGET_BRANCH} $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > public/version
    shell: bash